Updated workflow

diff --git a/.github/workflows/Build-Push.yml b/.github/workflows/Build-Push.yml
--- a/.github/workflows/Build-Push.yml
+++ b/.github/workflows/Build-Push.yml
@@ -87,16 +87,16 @@ jobs:
       - name: Build and Push Docker Image
         id: build
         run: |
-          export TZ=Asia/Kolkata
-          TIMESTAMP=$(date +%Y%m%d%H%M%S)
-          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
-          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${BRANCH_NAME}-${TIMESTAMP}"
-          LATEST_TAG="${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${BRANCH_NAME}-latest"
-          docker build -t ${IMAGE_TAG} -t ${LATEST_TAG} .
-          docker push ${IMAGE_TAG}
-          docker push ${LATEST_TAG}
-      # Output the constructed image tag to the GitHub Actions output variable.
-          echo "image_tag=${BRANCH_NAME}-${TIMESTAMP}" >> $GITHUB_OUTPUT
+               export TZ=Asia/Kolkata
+               TIMESTAMP=$(date +%Y%m%d%H%M%S)
+               BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
+               IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${BRANCH_NAME}-${TIMESTAMP}"
+               LATEST_TAG="${{ secrets.DOCKER_USERNAME }}/github-actions-backend:${BRANCH_NAME}-latest"
+               docker build -t ${IMAGE_TAG} -t ${LATEST_TAG} .
+               docker push ${IMAGE_TAG}
+               docker push ${LATEST_TAG}
+          # Output the constructed image tag to the GitHub Actions output variable.
+               echo "image_tag=${BRANCH_NAME}-${TIMESTAMP}" >> $GITHUB_OUTPUT
 
   update-manifests:
     needs: docker-build-push
@@ -167,22 +167,102 @@ jobs:
         env:
           IMAGE_TAG: ${{ needs.docker-build-push.outputs.image_tag }}
         run: |
+               git add .
+               if ! git diff-index --quiet HEAD --; then
+               if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+                git commit -m "Updated image tag to ${IMAGE_TAG} and incremented app versions"
+                git push origin main || echo "Push failed, possibly due to lack of permissions"
+               else
+          # Create a pull request if the branch is not main
+               TIMESTAMP=$(date +'%Y%m%d%H%M%S')
+               BRANCH_NAME="update-feature/${{ github.ref_name }}-${TIMESTAMP}"
+               git checkout -b $BRANCH_NAME
+               git commit -m "Update image tag to ${IMAGE_TAG} and incremented app versions"
+               git push -u origin $BRANCH_NAME
+          
+          # Create the pull request using GitHub CLI
+               gh pr create --title "Updated image tag to ${IMAGE_TAG}" --body "This PR updates the image tag to ${IMAGE_TAG}."
+               fi
+               else
+               echo "No changes detected."
+               fi
+
+  update-manifests-rollouts:
+    needs: docker-build-push
+    runs-on: ubuntu-latest
+    environment: backend-test-dev
+    steps:
+      # Checkout the Kubernetes manifests repository.
+      - name: Checkout Manifests
+        uses: actions/checkout@v4
+        with:
+          repository: yadnesh082024/spring-boot-backend-k8s-manifests
+          token: ${{ secrets.GH_PAT_UPDATE_MANIFEST }}
+
+      # Set up Git configuration for committing changes.
+      - name: Set up Git
+        run: |
+          git config --global user.name "GitHub-Actions-CI-Build"
+          git config --global user.email "user@gitHubActions.com"
+
+      # Update Helm values with the new image tag.
+      - name: Update Helm Values
+        env:
+          IMAGE_TAG: ${{ needs.docker-build-push.outputs.image_tag }}
+        run: |
+          sed -i "s/tag: .*/tag: ${IMAGE_TAG}/" spring-boot-helm-chart-argo-rollout/values.yaml
+
+      # Extract and increment appVersion for argo cd and rollouts.
+      - name: Increment appVersion
+        id: increment_version
+        run: |
+          increment_version() {
+            local chart_path=$1
+            local env_var_name=$2
+          
+            current_version=$(grep '^appVersion:' ${chart_path}/Chart.yaml | cut -d ' ' -f 2 | tr -d '"')
+            current_date=$(date +'%Y.%m')
+          
+            if [[ $current_version == $current_date* ]]; then
+              patch_number=$(echo $current_version | cut -d '.' -f 3)
+              patch_number=$((patch_number + 1))
+            else
+              patch_number=0
+            }
+          
+            new_version="${current_date}.${patch_number}"
+            echo "${env_var_name}=${new_version}" >> $GITHUB_ENV
+          }
+          increment_version "spring-boot-helm-chart-argo-rollout" "new_version_rollouts"
+
+      # Update appVersion in Chart.yaml
+      - name: Update appVersion in Chart.yaml
+        env:
+          NEW_VERSION_ROLLOUTS: ${{ env.new_version_rollouts }}
+        run: |
+          sed -i "s/^appVersion:.*/appVersion: \"${NEW_VERSION_ROLLOUTS}\"/" spring-boot-helm-chart-argo-rollout/Chart.yaml
+
+      # Check for changes, commit if necessary, and create a pull request if not on main.
+      - name: Check for Changes and Commit
+        env:
+          IMAGE_TAG: ${{ needs.docker-build-push.outputs.image_tag }}
+        run: |
           git add .
           if ! git diff-index --quiet HEAD --; then
-            if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
-              git commit -m "Updated image tag to ${IMAGE_TAG} and incremented app versions"
-              git push origin main || echo "Push failed, possibly due to lack of permissions"
-            else
-        # Create a pull request if the branch is not main
-              TIMESTAMP=$(date +'%Y%m%d%H%M%S')
-              BRANCH_NAME="update-feature/${{ github.ref_name }}-${TIMESTAMP}"
-              git checkout -b $BRANCH_NAME
-              git commit -m "Update image tag to ${IMAGE_TAG} and incremented app versions"
-              git push -u origin $BRANCH_NAME
-
-        # Create the pull request using GitHub CLI
-              gh pr create --title "Updated image tag to ${IMAGE_TAG}" --body "This PR updates the image tag to ${IMAGE_TAG}."
-            fi
+          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+           git commit -m "Updated image tag to ${IMAGE_TAG} and incremented app versions"
+           git push origin main || echo "Push failed, possibly due to lack of permissions"
           else
-            echo "No changes detected."
+          # Create a pull request if the branch is not main
+          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
+          BRANCH_NAME="update-feature/${{ github.ref_name }}-${TIMESTAMP}"
+          git checkout -b $BRANCH_NAME
+          git commit -m "Update image tag to ${IMAGE_TAG} and incremented app versions"
+          git push -u origin $BRANCH_NAME
+          
+          # Create the pull request using GitHub CLI
+          gh pr create --title "Updated image tag to ${IMAGE_TAG}" --body "This PR updates the image tag to ${IMAGE_TAG}."
+          fi
+          else
+          echo "No changes detected."
           fi
